### ISSUE TITLE
mobile:shell command not supported

### ISSUE THREAD

**Issue by ajschwieterman** [truongsinh/appium-flutter-driver#100]
Appium: v1.17.1
Appium Flutter Driver: v0.0.25
Platform: Android v11

`2020-09-28 20:15:16:537 - [Appium] Appium v1.17.1 creating new FlutterDriver (v0.0.23) session
2020-09-28 20:15:16:538 - [Appium] Applying relaxed security to 'FlutterDriver' as per server command line argument. All insecure features will be enabled unless explicitly disabled by --deny-insecure
2020-09-28 20:15:16:539 - [debug] [BaseDriver] Creating session with MJSONWP desired capabilities: {
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "app": "/Users/aaron.schwieterman/Apps/Android.apk",
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "noReset": true,
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "newCommandTimeout": 6000,
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "automationName": "Flutter",
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "platformName": "Android",
2020-09-28 20:15:16:539 - [debug] [BaseDriver]   "udid": "emulator-5554",
2020-09-28 20:15:16:571 - [debug] [BaseDriver]   "deviceName": "Android",
2020-09-28 20:15:16:575 - [debug] [BaseDriver]   "avd": "Pixel_3_XL_API_30"
2020-09-28 20:15:16:575 - [debug] [BaseDriver] }
...
2020-09-28 20:23:21:315 - [HTTP] --> POST /wd/hub/session/219ae018-26f9-4e3b-b151-13dc4318f84d/execute
2020-09-28 20:23:21:315 - [HTTP] {"script":"mobile:shell","args":[{"args":["ro.product.manufacturer"],"command":"getprop"}]}
2020-09-28 20:23:21:316 - [debug] [MJSONWP (219ae018)] Calling AppiumDriver.execute() with args: ["mobile:shell",[{"args":["ro.product.manufacturer"],"command":"getprop"}],"219ae018-26f9-4e3b-b151-13dc4318f84d"]
2020-09-28 20:23:21:316 - [debug] [FlutterDriver] Executing Flutter driver command 'execute'
2020-09-28 20:23:21:319 - [debug] [MJSONWP (219ae018)] Encountered internal error running command: Error: Command not support: "mobile:shell"
2020-09-28 20:23:21:319 - [debug] [MJSONWP (219ae018)]     at FlutterDriver.exports.execute (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/commands/execute.ts:15:11)
2020-09-28 20:23:21:319 - [debug] [MJSONWP (219ae018)]     at commandExecutor (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:330:9)
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at /Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/async-lock/lib/index.js:125:12
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at AsyncLock._promiseTry (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/async-lock/lib/index.js:249:31)
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at exec (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/async-lock/lib/index.js:124:9)
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at AsyncLock.acquire (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/async-lock/lib/index.js:140:3)
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at FlutterDriver.executeCommand (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:343:39)
2020-09-28 20:23:21:320 - [debug] [MJSONWP (219ae018)]     at FlutterDriver.executeCommand (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:123:22)
2020-09-28 20:23:21:321 - [debug] [MJSONWP (219ae018)]     at AppiumDriver.executeCommand (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/lib/appium.js:534:36)
2020-09-28 20:23:21:321 - [debug] [MJSONWP (219ae018)]     at runMicrotasks (<anonymous>)
2020-09-28 20:23:21:321 - [debug] [MJSONWP (219ae018)]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-09-28 20:23:21:321 - [debug] [MJSONWP (219ae018)]     at asyncHandler (/Users/aaron.schwieterman/.npm-packages/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)`

**Comment by andrii-rymar** [comment]
Are there any issues blocking appium-flutter-driver to have this feature implemented similar to [appium-android-driver](https://github.com/appium/appium-android-driver/blob/master/lib/commands/shell.js)?

**Comment by KazuCocoa** [comment]
You can send UIA2 commands in NATIVE_APP context
https://github.com/appium-userland/appium-flutter-driver#note
