### ISSUE TITLE
 Request failed due to unknown method: Method is not implemented

### ISSUE THREAD

**Issue by hbolin** [truongsinh/appium-flutter-driver#68]
An error occurred when I ran the demo at the following address：
https://github.com/truongsinh/appium-flutter-driver/tree/master/example/nodejs

The error:
2020-03-12T01:44:59.143Z ERROR webdriver: Request failed due to unknown method: Method is not implemented
    at getErrorFromResponseBody (D:\Tests\Appium\node_modules\webdriver\build\utils.js:124:10)
    at Request._callback (D:\Tests\Appium\node_modules\webdriver\build\request.js:111:64)
    at Request.self.callback (D:\Tests\Appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (D:\Tests\Appium\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (D:\Tests\Appium\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)
(node:10144) UnhandledPromiseRejectionWarning: unknown method: Method is not implemented
    at getErrorFromResponseBody (D:\Tests\Appium\node_modules\webdriver\build\utils.js:124:10)
    at Request._callback (D:\Tests\Appium\node_modules\webdriver\build\request.js:111:64)
    at Request.self.callback (D:\Tests\Appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at Request.<anonymous> (D:\Tests\Appium\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:311:20)
    at Request.EventEmitter.emit (domain.js:482:12)
    at IncomingMessage.<anonymous> (D:\Tests\Appium\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:417:28)

flutter doctor：
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

dart --version
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"

**Comment by hbolin** [comment]
automationName: "Flutter" should be add. like:
const opts2 = {
  port: 4723,
  capabilities: {
    platformName: "Android",
    platformVersion: "8",
    deviceName: "one plus",
    app: "D:/Tests/Appium/android-real-debug.apk",
    automationName: "Flutter"
  }
};
