### ISSUE TITLE
org.openqa.selenium.UnsupportedCommandException: Method is not implemented

### ISSUE THREAD

**Issue by rilham97** [truongsinh/appium-flutter-driver#85]
I create an automation using Java and cucumber and when I ran the program

```
  @When("user can input email")
  public void user_can_input_email() throws InterruptedException {
	  
	  assertEquals(driver.executeScript("flutter:checkHealth"), "ok");
	  driver.executeScript("flutter:clearTimeline");
	  driver.executeScript("flutter:forceGC");
	  
	  MobileElement element = find.byValueKey("EMAIL");
	  element.click();
	  driver.executeScript("flutter:enterText", "IlhamRama@gmail.com");
  }
```
Here the output

```
org.openqa.selenium.UnsupportedCommandException: Method is not implemented
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MTNB629', ip: '192.168.0.103', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.6'
Driver info: io.appium.java_client.android.AndroidDriver
Capabilities {appActivity: com.ais.teman_kondangan..., appPackage: com.ais.teman_kondangan, databaseEnabled: false, desired: {appActivity: com.ais.teman_kondangan..., appPackage: com.ais.teman_kondangan, deviceName: MI 8 SE, deviceid: 192.168.0.100:5555, noReset: false, platformName: android, platformVersion: 10.0, skipUnlock: true}, deviceApiLevel: 29, deviceManufacturer: Xiaomi, deviceModel: MI 8 SE, deviceName: 192.168.0.100:5555, deviceScreenDensity: 440, deviceScreenSize: 1080x2244, deviceUDID: 192.168.0.100:5555, deviceid: 192.168.0.100:5555, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: true, noReset: false, pixelRatio: 2.75, platform: LINUX, platformName: Android, platformVersion: 10, skipUnlock: true, statBarHeight: 85, takesScreenshot: true, viewportRect: {height: 1944, left: 0, top: 85, width: 1080}, warnings: {}, webStorageEnabled: false}
Session ID: 72071d43-5283-45aa-abdb-2b1aa452962f
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:489)
	at flutter_driver.FlutterTest_step.user_can_input_email(FlutterTest_step.java:25)
	at ?.user can input email(file:///D:/Coding-an/eclipse-workspace/coba_aplikasi/src/test/resources/login_flutter.feature:5)

```

**Comment by shibupanda** [comment]
@rilham97 
Could you please share complete Appium Logs using GIST.

**Comment by rilham97** [comment]
> @rilham97
> Could you please share complete Appium Logs using GIST.

Here the complete Appium Logs
<script src="https://gist.github.com/rilham97/06106bf2b1b57805fb7b154225bb3423.js"></script>

**Comment by shibupanda** [comment]
@rilham97 
use automationName = Flutter in the capability.

**Comment by rilham97** [comment]
@shibupanda Now the application can't be opened and got an error 

```
org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Could not find a driver for automationName 'Flutter' and platformName 'Android'. Please check your desired capabilities. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 103 milliseconds
```

**Comment by shibupanda** [comment]
@rilham97 
Is this an debug application. Looks flutterDriverExtension is not enabled.

Please enable it.

**Comment by rilham97** [comment]
Thank you, I can run automated testing clearly but now the problem is the android keyboard is not shown

**Comment by shibupanda** [comment]
@rilham97 
I think yes there is some caveats from Flutter itself but still you should able to send the keys to the text box.
Closing the issue for now please reopen if needed.

**Comment by sahanaprasad** [comment]
I have the same issue. I'm using debug application. automationName is also set to Flutter in the capabilities. flutterDriverExtension is also enabled. How can I solve the issue? @shibupanda @rilham97
