### ISSUE TITLE
Java flutter element return from finder does not indicate it is rendered from display

### ISSUE THREAD

**Issue by rex-wong** [truongsinh/appium-flutter-driver#87]
**Description**

It is found that the finder.byValueKey function will not return in error or null while such element is not rendered from screen or not exist.
Further check with driver log figured that no api call is raise to flutter driver with such function. In fact api call would only raise to flutter driver while further detail method or property is called like getText(). Such implementation is extremely hard to identify if the flutter widget is exist and allow to perform action or not

Meanwhile, if the element or widget is not yet rendered from screen, it takes long waiting time from flutter api reply for timeout

**Version of finder used under environment**
v0.0.4 binary zip from release

**enclosed with extracted appium driver log:**
```
[HTTP] --> POST /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/execute
[HTTP] {"script":"flutter:scroll","args":[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGV0YWlsQ29udGFpbmVyIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGV0YWlsQ29udGFpbmVyIn0"},{"durationMilliseconds":200,"dx":1,"dy":257,"frequency":30}]}
[debug] [MJSONWP (7563a48b)] Calling AppiumDriver.execute() with args: ["flutter:scroll",[{"ELEMENT":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGV0YWlsQ29udGFpbmVyIn0","element-6066-11e4-a52e-4f735466cecf":"eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGV0YWlsQ29udGFpbmVyIn0"},{"durationMilliseconds":200,"dx":1,"dy":257,"frequency":30}],"7563a48b-55a0-415f-99a6-b9d4ee5d29bd"]
[debug] [FlutterDriver] Executing Flutter driver command 'execute'
[debug] [FlutterDriver] >>> {"command":"scroll","finderType":"ByValueKey","keyValueType":"String","keyValueString":"txnDetailContainer","dx":1,"dy":257,"duration":200000,"frequency":30}
[debug] [FlutterDriver] <<< {"isError":false,"response":{},"type":"_extensionType","method":"ext.flutter.driver"} | previous command scroll
[debug] [MJSONWP (7563a48b)] Responding to client with driver.execute() result: {}
[HTTP] <-- POST /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/execute 200 230 ms - 74
[HTTP] 
[HTTP] --> GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTAifQ/text
[HTTP] {}
[debug] [MJSONWP (7563a48b)] Calling AppiumDriver.getText() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTAifQ","7563a48b-55a0-415f-99a6-b9d4ee5d29bd"]
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"ByValueKey","keyValueType":"String","keyValueString":"txnDate0"}
[debug] [FlutterDriver] <<< {"isError":false,"response":{"text":"09 JUL 2020"},"type":"_extensionType","method":"ext.flutter.driver"} | previous command get_text
[debug] [MJSONWP (7563a48b)] Responding to client with driver.getText() result: "09 JUL 2020"
[HTTP] <-- GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTAifQ/text 200 8 ms - 85
[HTTP] 
[HTTP] --> GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ/displayed
[HTTP] {}
[debug] [MJSONWP (7563a48b)] Calling AppiumDriver.elementDisplayed() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ","7563a48b-55a0-415f-99a6-b9d4ee5d29bd"]
[debug] [FlutterDriver] Executing Flutter driver command 'elementDisplayed'
[debug] [MJSONWP (7563a48b)] Encountered internal error running command: NotYetImplementedError: Method has not yet been implemented
[debug] [MJSONWP (7563a48b)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:323:13)
[debug] [MJSONWP (7563a48b)]     at FlutterDriver.executeCommand (/usr/local/lib/node_modules/appium/node_modules/appium-flutter-driver/lib/driver.ts:123:22)
[debug] [MJSONWP (7563a48b)]     at AppiumDriver.executeCommand (/usr/local/lib/node_modules/appium/lib/appium.js:534:36)
[debug] [MJSONWP (7563a48b)]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
[debug] [MJSONWP (7563a48b)]     at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:309:21)
[HTTP] <-- GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ/displayed 501 27 ms - 123
[HTTP] 
[HTTP] --> GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ/text
[HTTP] {}
[debug] [MJSONWP (7563a48b)] Calling AppiumDriver.getText() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ","7563a48b-55a0-415f-99a6-b9d4ee5d29bd"]
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
[debug] [FlutterDriver] >>> {"command":"get_text","finderType":"ByValueKey","keyValueType":"String","keyValueString":"txnDate1"}
[HTTP] <-- GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ/text - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/7563a48b-55a0-415f-99a6-b9d4ee5d29bd/element/eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ/text
[HTTP] {}
[debug] [MJSONWP (7563a48b)] Calling AppiumDriver.getText() with args: ["eyJmaW5kZXJUeXBlIjoiQnlWYWx1ZUtleSIsImtleVZhbHVlVHlwZSI6IlN0cmluZyIsImtleVZhbHVlU3RyaW5nIjoidHhuRGF0ZTEifQ","7563a48b-55a0-415f-99a6-b9d4ee5d29bd"]
[debug] [FlutterDriver] Executing Flutter driver command 'getText'
```

**Comment by shibupanda** [comment]
HI @rex-wong 
There is an open issue there in flutter.
So time being you can do have work around like **assume that if the wait times out that the element is not in the widget tree**
https://github.com/flutter/flutter/issues/15852

**Comment by rex-wong** [comment]
It is unfortunate that the API provide from  your side (the waitFor command) in Java client doesn't apply the timeout. Checked that the wait timeout should be a parameter from flutter API 

> HI @rex-wong
> There is an open issue there in flutter.
> So time being you can do have work around like **assume that if the wait times out that the element is not in the widget tree**
> [flutter/flutter#15852](https://github.com/flutter/flutter/issues/15852)

**Comment by shibupanda** [comment]
@rex-wong 
This has been added already.

**Comment by shibupanda** [comment]
Close as this is not a bug from appium-flutter-deriver.
